name: RDP Ngrok Gratis

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Mengaktifkan RDP Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Pasang Ngrok via Choco
      run: |
        choco install ngrok -y
    - name: Jalankan Koneksi RDP
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        net user youtubeuser YoutubeRDP123! /add
        net localgroup administrators youtubeuser /add
        ngrok tcp --authtoken $env:NGROK_TOKEN 3389
