name: RDP Upload YouTube Estafet

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 1. Konfigurasi Sistem RDP Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: 2. Buat Akun User Baru
      run: |
        net user youtubeuser YoutubeRDP123! /add
        net localgroup administrators youtubeuser /add
    - name: 3. Pasang Cloudflare via Choco
      run: |
        choco install cloudflared -y
    - name: 4. Jalankan Link Tunnel Instan
      run: |
        echo "============================================="
        echo "TUNGGU 10 DETIK, LALU CARI LINK DI BAWAH INI:"
        echo "============================================="
        cloudflared tunnel --url rdp://localhost:3389
